### ISSUE TITLE
Home Assistant Python package issue

### ISSUE THREAD

**Issue by havidarou** [SeraphicCorp/py-switchbot-api#1]
Hello,

I just noticed that the Python package source code added to Home Assistant is not exactly the same as the same version [tag](https://github.com/SeraphicCorp/py-switchbot-api/releases/tag/v1.2.1) in this repository.

For instance, at the beginning of the `__init__.py` there's this line:
```
OBSERVED_DEVICE_TYPES = [ "Remote", "Plug", "Plug Mini (US)", "Plug Mini (JP)"]
```

This makes the `SwitchBot Cloud` Home Assistant integration pretty useless as it depends on this to be expanded to new devices such as Bots, Meters, etc.

**Comment by SeraphicRav** [comment]
@havidarou Thank you for the issue report. I am sorry I did not notice that before.
I am not sure if I understood the issue. As only the remote and plugs are implemented in Home Assistant, bumping the version would not change anything.
The problem being in Home Assistant, it would be better to report the issue there but someone already bumped up the version in Home Assistant if my memory is correct. More implementation still need to be added there though.
